### PR TITLE
Showkase navigation breaks when preview contains a BackHandler

### LINKED ISSUE #247: Showkase browser doesn't work with empty @Preview BackHandler
If you have `BackHandler` which does nothing inside @Preview it breaks navigation for Showkase browser 

Snippet to reproduce: 
```
@Composable
fun ContentScreen(
    viewModel: ContentViewModel = androidx.lifecycle.viewmodel.compose.viewModel(),
) {
    Content(onBack = viewModel::onBack)
}

@Composable
fun Content(onBack: () -> Unit) {
    BackHandler(onBack = onBack)
}

@Preview
@Composable
fun ContentPreview() {
    Content(
        onBack = {},
    )
}

```

If you open `ContentPreview` from Showkase browser, it will not be possible to navigate back

### PR DESCRIPTION
**Pull request by vinaygaba**
Fixes #247 

Description of the issue

> If you have `BackHandler` which does nothing inside @Preview it breaks navigation for Showkase browser 

Snippet to reproduce: 
```
@Composable
fun ContentScreen(
    viewModel: ContentViewModel = androidx.lifecycle.viewmodel.compose.viewModel(),
) {
    Content(onBack = viewModel::onBack)
}

@Composable
fun Content(onBack: () -> Unit) {
    BackHandler(onBack = onBack)
}

@Preview
@Composable
fun ContentPreview() {
    Content(
        onBack = {},
    )
}

```

If you open `ContentPreview` from Showkase browser, it will not be possible to navigate back 

@airbnb/showkase-maintainers

### CODE REVIEW

File: sample/src/main/java/com/airbnb/android/showkasesample/Rows.kt [hunk 1]
```diff
@@ -186,6 +196,7 @@ fun ProductCardRow(imageUrl: String, title: String, subtitle: String) {
             )
 
         }
+        BackHandler(onBack = {  })
```
Comment (elihart) [inline sample/src/main/java/com/airbnb/android/showkasesample/Rows.kt:199]: maybe leave a comment so future readers know why this seemingly non functional code was added, and so it doesn't get deleted.

imo probably better to put it in an explicitly named sample

File: showkase/src/main/java/com/airbnb/android/showkase/ui/ShowkaseBrowserApp.kt [hunk 2]
```diff
@@ -69,7 +74,16 @@ internal fun ShowkaseBrowserApp(
     val lightModeConfiguration = Configuration(LocalConfiguration.current).apply {
         uiMode = Configuration.UI_MODE_NIGHT_NO
     }
-    CompositionLocalProvider(LocalConfiguration provides lightModeConfiguration) {
+    val lifecycleOwner = LocalLifecycleOwner.current
+    CompositionLocalProvider(
+        LocalConfiguration provides lightModeConfiguration,
+        LocalInspectionMode provides true,
+        LocalOnBackPressedDispatcherOwner provides object: OnBackPressedDispatcherOwner {
```
Comment (elihart) [inline showkase/src/main/java/com/airbnb/android/showkase/ui/ShowkaseBrowserApp.kt:81]: better to remember this object?

Comment (elihart) [reply showkase/src/main/java/com/airbnb/android/showkase/ui/ShowkaseBrowserApp.kt:81]: also, leave a comment about why this is necessary and what the purpose is?
